name: Increase versionCode and trigger Jenkins

on:
  push:
    branches:
      - beta-firebase

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Increase versionCode
      run: |
        cd app
        version=$(grep -m 1 "^def version" build.gradle | tr -dc '0-9')
        newVersion=$((version + 1))
        sed -i "s/\(def version[[:space:]]*\)[0-9]\+/\1$newVersion/" build.gradle

    - name: Add changes to git
      run: |
        git add app/build.gradle

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Increase versionCode"
        if [[ `git diff --stat --staged` != '' ]]; then
          git push https://${{ secrets.REPO_TOKEN }}@github.com/tim-khakimov/waveform-editor.git HEAD:beta-firebase
        fi

    - name: Trigger Jenkins
      run: |
        curl -X GET "http://81.200.151.166:8080/job/WaveForm_Build_Beta_Firebase/build?token=test_token_for_build_beta_firebase" -u timur:timur
